#!/usr/bin/env python3
"""
CNBC Daily - a local copy you can run on your own computer.

Double-click this file (or run "python3 CNBC-App.py" in a terminal). It starts
a small web server on your machine, opens your browser, and shows CNBC
headlines and stock prices. Nothing is installed and nothing is sent anywhere
except to CNBC's own public feeds.

Press Ctrl+C in the terminal window to stop it.

This file is generated by tools/build-standalone.mjs - edit the sources in
public/ and standalone/server_template.py, then rebuild.

Not affiliated with or endorsed by CNBC.
"""

import base64
import json
import re
import socket
import sys
import threading
import time
import urllib.parse
import urllib.request
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# --------------------------------------------------------------------------
# embedded front end (filled in at build time)
# --------------------------------------------------------------------------

ASSETS = __EMBEDDED_ASSETS__

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
}

# --------------------------------------------------------------------------
# CNBC endpoints
# --------------------------------------------------------------------------

QUOTE_URL = "https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol"

BROWSER_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, text/html, */*",
    "Accept-Language": "en-US,en;q=0.9",
}

FEEDS = {
    "top": ("100003114", "Top news"),
    "markets": ("20409666", "Markets"),
    "business": ("10001147", "Business"),
    "economy": ("20910258", "Economy"),
    "tech": ("19854910", "Technology"),
    "finance": ("10000664", "Finance"),
    "earnings": ("15839135", "Earnings"),
    "investing": ("15839069", "Investing"),
    "politics": ("10000113", "Politics"),
    "world": ("100727362", "World"),
    "health": ("10000108", "Health"),
    "realestate": ("10000115", "Real estate"),
    "energy": ("19836768", "Energy"),
}

TAPE_SYMBOLS = [
    ".DJI", ".SPX", ".IXIC", ".RUT", ".VIX",
    "US10Y", "@CL.1", "@GC.1", "BTC.CM=", "EUR=",
]

DEFAULT_WATCHLIST = ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "JPM", "JNJ", "KO"]

SYMBOL_RE = re.compile(r"^[A-Z0-9.\-=@^:&]+$")

# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def http_get(url, timeout=12):
    """Plain GET with a browser user agent. Returns the body as text."""
    request = urllib.request.Request(url, headers=BROWSER_HEADERS)
    with urllib.request.urlopen(request, timeout=timeout) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def num(value):
    """CNBC sends numbers as display strings: '1,234.56', '+0.42', 'UNCH'."""
    if value is None:
        return None
    raw = str(value).strip()
    if not raw:
        return None
    if raw.upper() == "UNCH":
        return 0.0
    if raw.upper() in ("N/A", "NA", "--", "-"):
        return None
    cleaned = re.sub(r"[,%\s+]", "", raw)
    try:
        return float(cleaned)
    except ValueError:
        return None


def market_status_label(code):
    return {
        "REG_MKT": "Market open",
        "PRE_MKT": "Pre-market",
        "POST_MKT": "After hours",
        "MKT_CLOSED": "Market closed",
    }.get(str(code or "").upper(), "")


def sanitize_symbols(raw, limit=40):
    seen = []
    for part in re.split(r"[|,]", raw or ""):
        symbol = part.strip().upper()
        if symbol and len(symbol) <= 16 and SYMBOL_RE.match(symbol) and symbol not in seen:
            seen.append(symbol)
    return seen[:limit]


# --------------------------------------------------------------------------
# quotes
# --------------------------------------------------------------------------


def normalize_quote(raw):
    extended_raw = raw.get("ExtendedMktQuote") or None
    extended = None
    if extended_raw and num(extended_raw.get("last")) is not None:
        extended = {
            "last": num(extended_raw.get("last")),
            "change": num(extended_raw.get("change")),
            "changePct": num(extended_raw.get("change_pct")),
            "label": market_status_label(extended_raw.get("type")) or "Extended hours",
        }

    return {
        "symbol": raw.get("symbol") or "",
        "name": raw.get("name") or raw.get("shortName") or raw.get("symbol") or "",
        "last": num(raw.get("last")),
        "change": num(raw.get("change")),
        "changePct": num(raw.get("change_pct")),
        "prevClose": num(raw.get("previous_day_closing")),
        "open": num(raw.get("open")),
        "high": num(raw.get("high")),
        "low": num(raw.get("low")),
        "volume": num(raw.get("volume")),
        "currency": raw.get("currencyCode"),
        "marketStatus": market_status_label(raw.get("curmktstatus")),
        "asOf": raw.get("last_timedate") or raw.get("last_time"),
        "extended": extended,
        "source": "cnbc",
    }


def fetch_cnbc_quotes(symbols):
    if not symbols:
        return []
    params = urllib.parse.urlencode({
        "symbols": "|".join(symbols),
        "requestMethod": "itv",
        "noform": "1",
        "partnerId": "2",
        "fund": "1",
        "exthrs": "1",
        "output": "json",
        "events": "1",
    })
    body = json.loads(http_get(QUOTE_URL + "?" + params))
    result = (body.get("FormattedQuoteResult") or {}).get("FormattedQuote")
    if not result:
        return []
    if isinstance(result, dict):      # a single-symbol request returns an object
        result = [result]
    return [normalize_quote(q) for q in result if q and q.get("symbol")]


def fetch_stooq_quote(symbol):
    """Backup source: end-of-day CSV. Ordinary listed shares and ETFs only."""
    if not re.match(r"^[A-Z][A-Z0-9.\-]{0,9}$", symbol):
        return None
    stooq_symbol = symbol.lower().replace(".", "-") + ".us"
    try:
        text = http_get(
            "https://stooq.com/q/d/l/?s=" + urllib.parse.quote(stooq_symbol) + "&i=d",
            timeout=8,
        )
    except Exception:
        return None

    rows = [line for line in text.strip().split("\n") if line]
    if len(rows) < 3:
        return None

    latest, previous = rows[-1].split(","), rows[-2].split(",")
    try:
        close, prev_close = float(latest[4]), float(previous[4])
    except (IndexError, ValueError):
        return None
    if prev_close == 0:
        return None

    change = close - prev_close
    def maybe(index):
        try:
            return float(latest[index])
        except (IndexError, ValueError):
            return None

    return {
        "symbol": symbol, "name": symbol,
        "last": close, "change": change, "changePct": change / prev_close * 100,
        "prevClose": prev_close, "open": maybe(1), "high": maybe(2), "low": maybe(3),
        "volume": maybe(5), "currency": "USD", "marketStatus": "End of day",
        "asOf": latest[0], "extended": None, "source": "stooq",
    }


def get_quotes(raw_symbols):
    wanted = sanitize_symbols(raw_symbols)
    if not wanted:
        return {"quotes": [], "warnings": ["No valid symbols requested."]}

    warnings, quotes = [], []
    try:
        quotes = fetch_cnbc_quotes(wanted)
    except Exception as error:
        warnings.append("CNBC quotes unavailable (%s)." % error)

    found = {q["symbol"].upper() for q in quotes}
    missing = [s for s in wanted if s not in found]

    if missing:
        backups = [fetch_stooq_quote(s) for s in missing[:25]]
        usable = [b for b in backups if b]
        if usable:
            quotes.extend(usable)
            warnings.append(
                "Showing end-of-day backup prices for %d symbol(s)." % len(usable)
            )

    order = {symbol: index for index, symbol in enumerate(wanted)}
    quotes.sort(key=lambda q: order.get(q["symbol"].upper(), 999))
    return {"quotes": quotes, "warnings": warnings}


# --------------------------------------------------------------------------
# news
# --------------------------------------------------------------------------

NAMED_ENTITIES = {
    "amp": "&", "lt": "<", "gt": ">", "quot": '"', "apos": "'", "nbsp": " ",
    "rsquo": "’", "lsquo": "‘", "ldquo": "“", "rdquo": "”",
    "mdash": "—", "ndash": "–", "hellip": "…", "trade": "™",
}


def decode_entities(text):
    def replace(match):
        code = match.group(1)
        if code.startswith("#"):
            try:
                value = int(code[2:], 16) if code[1] in "xX" else int(code[1:], 10)
                return chr(value)
            except (ValueError, OverflowError):
                return match.group(0)
        return NAMED_ENTITIES.get(code.lower(), match.group(0))

    return re.sub(r"&(#x?[0-9a-fA-F]+|[a-zA-Z]+);", replace, text)


def tag_text(block, tag):
    match = re.search(r"<%s\b[^>]*>(.*?)</%s>" % (tag, tag), block, re.S | re.I)
    if not match:
        return ""
    value = match.group(1).strip()
    cdata = re.match(r"^<!\[CDATA\[(.*?)\]\]>$", value, re.S)
    if cdata:
        value = cdata.group(1)
    value = re.sub(r"<[^>]+>", "", value)
    return re.sub(r"\s+", " ", decode_entities(value)).strip()


def parse_rss(xml):
    items = []
    for match in re.finditer(r"<item\b[^>]*>(.*?)</item>", xml, re.S | re.I):
        block = match.group(1)
        title = tag_text(block, "title")
        link = tag_text(block, "link")
        if not title or not re.match(r"^https?://", link, re.I):
            continue

        published = tag_text(block, "pubDate")
        iso = None
        if published:
            try:
                from email.utils import parsedate_to_datetime
                iso = parsedate_to_datetime(published).isoformat()
            except Exception:
                iso = None

        items.append({
            "id": tag_text(block, "guid") or link,
            "title": title,
            "link": link,
            "summary": tag_text(block, "description")[:400],
            "published": iso,
        })
    return items


def fetch_feed(slug):
    feed_id = FEEDS[slug][0]
    return parse_rss(http_get("https://www.cnbc.com/id/%s/device/rss/rss.html" % feed_id))


def get_news(slug, limit=30):
    category = slug if slug in FEEDS else "top"
    warnings, items, used = [], [], category

    try:
        items = fetch_feed(category)
    except Exception as error:
        warnings.append(str(error))

    if not items and category != "top":
        warnings.append("No stories in %s; showing Top news." % FEEDS[category][1])
        used = "top"
        try:
            items = fetch_feed("top")
        except Exception as error:
            warnings.append(str(error))

    limit = max(1, min(int(limit or 30), 60))
    return {
        "category": used,
        "label": FEEDS[used][1],
        "items": items[:limit],
        "warnings": warnings,
    }


# --------------------------------------------------------------------------
# a very small cache, so clicking Refresh does not hammer CNBC
# --------------------------------------------------------------------------

_cache = {}
_cache_lock = threading.Lock()


def cached(key, ttl_seconds, produce):
    now = time.time()
    with _cache_lock:
        hit = _cache.get(key)
        if hit and now - hit[0] < ttl_seconds:
            return hit[1]
    value = produce()
    with _cache_lock:
        _cache[key] = (now, value)
    return value


# --------------------------------------------------------------------------
# web server
# --------------------------------------------------------------------------


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *args):
        pass  # keep the terminal window quiet

    def _send(self, status, body, content_type):
        payload = body if isinstance(body, bytes) else body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        self.wfile.write(payload)

    def _send_json(self, status, payload):
        self._send(status, json.dumps(payload), "application/json; charset=utf-8")

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        query = urllib.parse.parse_qs(parsed.query)
        path = parsed.path

        if path == "/api/quotes":
            if query.get("set", [""])[0] == "tape":
                requested = "|".join(TAPE_SYMBOLS)
            else:
                requested = query.get("symbols", ["|".join(DEFAULT_WATCHLIST)])[0]
            try:
                result = cached("q:" + requested, 15, lambda: get_quotes(requested))
                self._send_json(200, dict(ok=True, updated=time.strftime("%Y-%m-%dT%H:%M:%SZ"), **result))
            except Exception as error:
                self._send_json(502, {"ok": False, "error": str(error), "quotes": [], "warnings": []})
            return

        if path == "/api/news":
            category = query.get("category", ["top"])[0]
            limit = query.get("limit", ["30"])[0]
            try:
                result = cached("n:%s:%s" % (category, limit), 120, lambda: get_news(category, limit))
                self._send_json(200, dict(
                    ok=True,
                    updated=time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    categories=[{"slug": s, "label": f[1]} for s, f in FEEDS.items()],
                    **result,
                ))
            except Exception as error:
                self._send_json(502, {"ok": False, "error": str(error), "items": [], "warnings": []})
            return

        name = "index.html" if path == "/" else path.lstrip("/")
        if name in ASSETS:
            extension = "." + name.rsplit(".", 1)[-1]
            self._send(
                200,
                base64.b64decode(ASSETS[name]),
                CONTENT_TYPES.get(extension, "application/octet-stream"),
            )
            return

        self._send(404, "Not found", "text/plain; charset=utf-8")


def find_port(preferred=8765):
    for port in range(preferred, preferred + 40):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            if probe.connect_ex(("127.0.0.1", port)) != 0:
                return port
    return 0  # let the OS choose


def main():
    port = find_port()
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    port = server.server_address[1]
    url = "http://localhost:%d" % port

    print("")
    print("  CNBC Daily is running.")
    print("")
    print("  Open this in your browser:  %s" % url)
    print("  To stop it, press Ctrl+C in this window.")
    print("")

    threading.Timer(1.0, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n  Stopped. You can close this window.\n")
        server.shutdown()


if __name__ == "__main__":
    if sys.version_info < (3, 7):
        sys.exit("This needs Python 3.7 or newer.")
    main()
